version: '3.8'
services:
    php-apache-environment:
        image : php:8.0-apache
        volumes:
            - ./php:/var/www/html/
        ports:
            - 80:80
    db:
        container_name: db
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: api_get
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        ports:
            - "9906:3306"
        networks:
            - default
    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080

